// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SearchAChurch.Api.Data;

#nullable disable

namespace SearchAChurch.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008124450_AddProfileManagementEntities")]
    partial class AddProfileManagementEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("ClientPort")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.Church", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Denomination")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FormattedAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlaceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SocialFacebook")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SocialInstagram")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("WorshipStyle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimStatus");

                    b.HasIndex("IsActive");

                    b.HasIndex("PlaceId")
                        .IsUnique()
                        .HasFilter("place_id IS NOT NULL");

                    b.HasIndex("VerifiedByUserId");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("churches", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.ChurchClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TosAccepted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("TosAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TosVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.HasIndex("ChurchId", "Status");

                    b.ToTable("church_claims", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.ChurchMeetingSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("pt");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("DayOfWeek");

                    b.ToTable("church_meeting_schedules", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.ChurchTag", b =>
                {
                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChurchId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("church_tags", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.ClaimAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("ClientPort")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("RetentionUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationMetadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("RetentionUntil");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("UserId");

                    b.ToTable("claim_audit_logs", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.ClaimEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FileHashSha256")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RawDataOrUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("claim_evidences", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.DisputeCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ChallengerAverbationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChallengerDocumentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ChallengerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("IncumbentAverbationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IncumbentDocumentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("IncumbentUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengerUserId");

                    b.HasIndex("ChurchId");

                    b.HasIndex("DeadlineAt");

                    b.HasIndex("IncumbentUserId");

                    b.HasIndex("Status");

                    b.ToTable("dispute_cases", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.PasswordResetOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_otps", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.TagCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("tag_catalogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Category = 1,
                            Code = "rampa_acesso",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Acesso pleno a cadeirantes e pessoas com mobilidade reduzida.",
                            DisplayOrder = 1,
                            IconName = "accessible",
                            IsActive = true,
                            Name = "Rampa de Acesso"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Category = 1,
                            Code = "interprete_libras",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Inclusão de surdos e deficientes auditivos durante o culto.",
                            DisplayOrder = 2,
                            IconName = "sign_language",
                            IsActive = true,
                            Name = "Intérprete de LIBRAS"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Category = 1,
                            Code = "banheiro_acessivel",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Instalações sanitárias projetadas para acessibilidade.",
                            DisplayOrder = 3,
                            IconName = "wc",
                            IsActive = true,
                            Name = "Banheiro Adaptado"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Category = 1,
                            Code = "elevador_acessivel",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Acesso facilitado entre diferentes andares do templo.",
                            DisplayOrder = 4,
                            IconName = "elevator",
                            IsActive = true,
                            Name = "Elevador / Plataforma"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            Category = 1,
                            Code = "audiodescricao",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Apoio para pessoas com deficiência visual.",
                            DisplayOrder = 5,
                            IconName = "hearing",
                            IsActive = true,
                            Name = "Recurso de Audiodescrição"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Category = 2,
                            Code = "estacionamento_proprio",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Vagas gratuitas ou privativas para fiéis e visitantes.",
                            DisplayOrder = 6,
                            IconName = "local_parking",
                            IsActive = true,
                            Name = "Estacionamento Próprio"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Category = 2,
                            Code = "ar_condicionado",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Templo totalmente equipado com climatização.",
                            DisplayOrder = 7,
                            IconName = "ac_unit",
                            IsActive = true,
                            Name = "Ambiente Climatizado"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Category = 2,
                            Code = "espaco_kids_bercario",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sala dedicada a bebês e crianças pequenas com monitoria.",
                            DisplayOrder = 8,
                            IconName = "child_care",
                            IsActive = true,
                            Name = "Espaço Kids & Berçário"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Category = 2,
                            Code = "transmissao_online",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Transmissão em tempo real via YouTube, Facebook ou site.",
                            DisplayOrder = 9,
                            IconName = "live_tv",
                            IsActive = true,
                            Name = "Transmissão Ao Vivo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Category = 2,
                            Code = "refeitorio_cantina",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Espaço comunitário para comunhão e alimentação pós-culto.",
                            DisplayOrder = 10,
                            IconName = "restaurant",
                            IsActive = true,
                            Name = "Refeitório / Cantina"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Category = 3,
                            Code = "ministerio_jovens",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Reuniões, células e eventos focados no público jovem.",
                            DisplayOrder = 11,
                            IconName = "groups",
                            IsActive = true,
                            Name = "Ministério de Jovens"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Category = 3,
                            Code = "ministerio_infantil",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Culto infantil paralelo e atividades pedagógicas.",
                            DisplayOrder = 12,
                            IconName = "child_friendly",
                            IsActive = true,
                            Name = "Ministério Infantil"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Category = 3,
                            Code = "ministerio_casais",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cursos, encontros e acompanhamento para famílias.",
                            DisplayOrder = 13,
                            IconName = "favorite",
                            IsActive = true,
                            Name = "Ministério de Casais"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Category = 3,
                            Code = "escola_biblica",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Aulas sistemáticas de estudo das Escrituras aos domingos.",
                            DisplayOrder = 14,
                            IconName = "menu_book",
                            IsActive = true,
                            Name = "Escola Bíblica (EBD)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            Category = 3,
                            Code = "acao_social",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Distribuição de cestas básicas, roupas e amparo a vulneráveis.",
                            DisplayOrder = 15,
                            IconName = "volunteer_activism",
                            IsActive = true,
                            Name = "Ação Social Comunitária"
                        });
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsVerifiedRepresentative")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DefaultRadiusKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(10.0);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Denomination")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAnonymous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PreferredLanguages")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorshipStyle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.UserProfileTag", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserProfileId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("user_profile_tags", (string)null);
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("SearchAChurch.Api.Data.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.Church", b =>
                {
                    b.HasOne("SearchAChurch.Api.Data.Entities.User", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.ChurchClaim", b =>
                {
                    b.HasOne("SearchAChurch.Api.Data.Entities.Church", "Church")
                        .WithMany("Claims")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchAChurch.Api.Data.Entities.User", "User")
                        .WithMany("ChurchClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.ChurchMeetingSchedule", b =>
                {
                    b.HasOne("SearchAChurch.Api.Data.Entities.Church", "Church")
                        .WithMany("MeetingSchedules")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.ChurchTag", b =>
                {
                    b.HasOne("SearchAChurch.Api.Data.Entities.Church", "Church")
                        .WithMany("ChurchTags")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchAChurch.Api.Data.Entities.TagCatalog", "Tag")
                        .WithMany("ChurchTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.ClaimAuditLog", b =>
                {
                    b.HasOne("SearchAChurch.Api.Data.Entities.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SearchAChurch.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Church");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.ClaimEvidence", b =>
                {
                    b.HasOne("SearchAChurch.Api.Data.Entities.ChurchClaim", "Claim")
                        .WithMany("Evidences")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.DisputeCase", b =>
                {
                    b.HasOne("SearchAChurch.Api.Data.Entities.User", "ChallengerUser")
                        .WithMany()
                        .HasForeignKey("ChallengerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SearchAChurch.Api.Data.Entities.Church", "Church")
                        .WithMany("DisputeCases")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchAChurch.Api.Data.Entities.User", "IncumbentUser")
                        .WithMany()
                        .HasForeignKey("IncumbentUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChallengerUser");

                    b.Navigation("Church");

                    b.Navigation("IncumbentUser");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.PasswordResetOtp", b =>
                {
                    b.HasOne("SearchAChurch.Api.Data.Entities.User", "User")
                        .WithMany("PasswordResetOtps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("SearchAChurch.Api.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.UserProfile", b =>
                {
                    b.HasOne("SearchAChurch.Api.Data.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SearchAChurch.Api.Data.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.UserProfileTag", b =>
                {
                    b.HasOne("SearchAChurch.Api.Data.Entities.TagCatalog", "Tag")
                        .WithMany("UserProfileTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchAChurch.Api.Data.Entities.UserProfile", "UserProfile")
                        .WithMany("UserProfileTags")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.Church", b =>
                {
                    b.Navigation("ChurchTags");

                    b.Navigation("Claims");

                    b.Navigation("DisputeCases");

                    b.Navigation("MeetingSchedules");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.ChurchClaim", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.TagCatalog", b =>
                {
                    b.Navigation("ChurchTags");

                    b.Navigation("UserProfileTags");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ChurchClaims");

                    b.Navigation("PasswordResetOtps");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SearchAChurch.Api.Data.Entities.UserProfile", b =>
                {
                    b.Navigation("UserProfileTags");
                });
#pragma warning restore 612, 618
        }
    }
}
